version: "3.8"

services:
  server:
    image: pern-store-server
    container_name: pern-store-server
    build:
      context: ./server
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=pern-store-db
      - POSTGRES_DB=pernstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminuser
    volumes:
      # Maps the server directory to
      # the working directory in the container
      - ./server:/usr/src/app
      # Maps the node_modules directory to
      # the working directory in the container
      # and also fixes bcrypt error
      - /usr/src/app/node_modules
    ports:
      - 9000:9000
    depends_on:
      - database
    networks:
      - default
  database:
    container_name: pern-store-db
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    environment:
      # other environment variables is in ./server/.env file
      - POSTGRES_PASSWORD=adminuser
    ports:
      - 7890:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      # When the PostgreSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory
      # seed the database with the init.sql file
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
  nginx:
    image: nginx:alpine
    container_name: pern-store-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - default

volumes:
  db:
    driver: local

networks:
  default:
    driver: bridge
    