version: "3.8"

services:
  server:
    image: pern-store-server
    container_name: pern-store-server
    build:
      context: ./server
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_DB=pernstore
      - POSTGRES_USER=adminuser
      - POSTGRES_PASSWORD=adminuser
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9000:9000
