version: "3.8"

services:
  server:
    image: pern-store-server
    container_name: pern-store-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    # restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=pern-store-db
      - POSTGRES_DB=pernstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminuser
      # - POSTGRES_PORT=7890
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9000:9000
    depends_on:
      - database
  database:
    container_name: pern-store-db
    image: postgres
    restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_PASSWORD=adminuser
    ports:
      - 7890:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dhatguy@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwertyuiop"
    ports:
      - "16543:80"
    depends_on:
      - database
  nginx:
    image: nginx:alpine
    container_name: pern-store-nginx
    ports:
      - 9000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - server
volumes:
  db:
    driver: local
networks:
  default:
    external:
      name: pern-store-network
